CREATE DATABASE e_commerceINGSW;
USE e_commerceINGSW;

CREATE TABLE `UTENTE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) NOT NULL,
  `COGNOME` varchar(20) NOT NULL,
  `NUMERO_TELEFONO` char(15) DEFAULT NULL,
  `RUOLO` enum('admin','cliente') NOT NULL DEFAULT 'cliente',
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `CITTA` varchar(50) DEFAULT NULL,
  `CAP` char(5) DEFAULT NULL,
  `VIA` varchar(50) DEFAULT NULL,
  `NUMERO_CIVICO` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  UNIQUE KEY `NUMERO_TELEFONO_UNIQUE` (`NUMERO_TELEFONO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CATEGORIA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  `DESCRIZIONE` text,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME_UNIQUE` (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODOTTO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  `DESCRIZIONE` text,
  `PREZZO` decimal(10,2) NOT NULL,
  `QUANTITA_DISPONIBILE` int NOT NULL,
  `IMMAGINE_URL` varchar(500) DEFAULT NULL,             
  `ID_CATEGORIA` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_CATEGORIA_idx` (`ID_CATEGORIA`),
  CONSTRAINT `prodotto_categoria_fk` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `CATEGORIA` (`ID`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ORDINE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DATA` datetime NOT NULL DEFAULT NOW(),
  `STATUS` enum('in_lavorazione','completato','annullato') NOT NULL DEFAULT 'in_lavorazione',
  `ID_UTENTE` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_UTENTE_idx` (`ID_UTENTE`),
  CONSTRAINT `ordine_utente_fk` FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ORDINE_PRODOTTO` (
  `ID_PRODOTTO` int NOT NULL,
  `ID_ORDINE` int NOT NULL,
  `QUANTITA` int NOT NULL,
  `PREZZO_UNITARIO` decimal(10,2) NOT NULL,
  PRIMARY KEY (`ID_PRODOTTO`,`ID_ORDINE`),
  KEY `ID_ORDINE_idx` (`ID_ORDINE`),
  CONSTRAINT `ordine_prodotto_ordine_fk` FOREIGN KEY (`ID_ORDINE`) REFERENCES `ORDINE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ordine_prodotto_prodotto_fk` FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `WISHLIST` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_UTENTE` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `wishlist_utente_fk_idx` (`ID_UTENTE`),
  CONSTRAINT `wishlist_utente_fk` FOREIGN KEY (`ID_UTENTE`) REFERENCES `UTENTE` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `WISHLIST_PRODOTTO` (
  `ID_PRODOTTO` int NOT NULL,
  `ID_WISHLIST` int NOT NULL,
  PRIMARY KEY (`ID_PRODOTTO`,`ID_WISHLIST`),
  KEY `wishlist_fk_idx` (`ID_WISHLIST`),
  CONSTRAINT `wishlist_prodotto_prodotto_fk` FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `PRODOTTO` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `wishlist_prodotto_wishlist_fk` FOREIGN KEY (`ID_WISHLIST`) REFERENCES `WISHLIST` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
